### ISSUE TITLE
Automatically create a project

### ISSUE THREAD

**Issue by Cerabbite** [JakubGluszek/intentio#2]
I just spend 5 minutes entering what I had to do and linking them to projects. Not realizing that inorder to add a project I had to first click the plus button. So I would reccomend that when you enter a project name that is not yet an existing project you create that project automatically

**Comment by JakubGluszek** [comment]
You're totally right, it should work that way.
I'll make sure to take such thing into consideration for next version release, since I'll be implementing the queue system a little bit differently.
